// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SalesForce.DataAccess.Migrations
{
    [DbContext(typeof(SalesForceDBContext))]
    [Migration("20211113212304_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConfiguracaoCampos", b =>
                {
                    b.Property<int>("CodEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Tela")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Campo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Visivel")
                        .HasColumnType("bit");

                    b.HasKey("CodEmpresa", "Tela", "Campo");

                    b.ToTable("ConfiguracaoCampos");
                });

            modelBuilder.Entity("Grupo", b =>
                {
                    b.Property<int>("CodEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("CodGrupo")
                        .HasColumnType("int");

                    b.Property<string>("NomeGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodEmpresa", "CodGrupo");

                    b.ToTable("CadGrupo");
                });

            modelBuilder.Entity("Usuarios", b =>
                {
                    b.Property<string>("Usuario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("GrupoCodEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoCodGrupo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Usuario");

                    b.HasIndex("GrupoCodEmpresa", "GrupoCodGrupo");

                    b.ToTable("CadUsuario");
                });

            modelBuilder.Entity("Usuarios", b =>
                {
                    b.HasOne("Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoCodEmpresa", "GrupoCodGrupo");

                    b.Navigation("Grupo");
                });
#pragma warning restore 612, 618
        }
    }
}
