// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesForceApi;

namespace SalesForceApi.Migrations
{
    [DbContext(typeof(SalesForceDBContext))]
    [Migration("20211108154905_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConfiguracaoCampos", b =>
                {
                    b.Property<int>("CodEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Tela")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Campo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Visivel")
                        .HasColumnType("bit");

                    b.HasKey("CodEmpresa", "Tela", "Campo");

                    b.ToTable("Campos");
                });
#pragma warning restore 612, 618
        }
    }
}
