// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesForceApi.DAO;

namespace SalesForceApi.Migrations
{
    [DbContext(typeof(ConfiguracaoCamposDAO))]
    partial class ConfiguracaoCamposDAOModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SalesForceApi.Models.ConfiguracaoCampos", b =>
                {
                    b.Property<int>("CodEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Tela")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Campo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Visivel")
                        .HasColumnType("bit");

                    b.HasKey("CodEmpresa", "Tela", "Campo");

                    b.ToTable("Campos");
                });

            modelBuilder.Entity("SalesForceApi.Models.UsuariosPermissao", b =>
                {
                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfgCampoCampo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CfgCampoCodEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("CfgCampoTela")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Usuario");

                    b.HasIndex("CfgCampoCodEmpresa", "CfgCampoTela", "CfgCampoCampo");

                    b.ToTable("UsuariosPermissao");
                });

            modelBuilder.Entity("SalesForceApi.Models.UsuariosPermissao", b =>
                {
                    b.HasOne("SalesForceApi.Models.ConfiguracaoCampos", "CfgCampo")
                        .WithMany("UsuariosPermissao")
                        .HasForeignKey("CfgCampoCodEmpresa", "CfgCampoTela", "CfgCampoCampo");

                    b.Navigation("CfgCampo");
                });

            modelBuilder.Entity("SalesForceApi.Models.ConfiguracaoCampos", b =>
                {
                    b.Navigation("UsuariosPermissao");
                });
#pragma warning restore 612, 618
        }
    }
}
